

DELETE https://young-fjord-17804.herokuapp.com/users/LisaAdmin2/movies/Downsizing
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU2OTIyNDE0MjAxYzdiNTk2YWM3ZTciLCJOYW1lIjoiTGlzYUFkbWluMiIsIlBhc3N3b3JkIjoiJDJiJDEwJHRUL1ExSGlnMHdmQW5UT0pJOU96Y3VIeEdZbm91c3lseE5pZ1oyUEUwekVFclNybU51VXQuIiwiRW1haWwiOiJsaXNhQGdtYWlsMy5kZSIsIkJpcnRoZGF5IjoiMTk4NC0wNi0wN1QwMDowMDowMC4wMDBaIiwiRmF2b3JpdGVNb3ZpZXMiOlsiNjI0ZTk1NjkxMjJkZWVkMzc4MGYxZjVmIiwiNjI0ZTliOTAxMjJkZWVkMzc4MGYxZjY3IiwiNjI0ZTlhZTUxMjJkZWVkMzc4MGYxZjY2Il0sIl9fdiI6MCwiaWF0IjoxNjUyMTcwMTk1LCJleHAiOjE2NTI3NzQ5OTUsInN1YiI6Ikxpc2FBZG1pbjIifQ.P8MQRR6bO4bPHv3owcSFZu1es8AEaUTzxI0bTxwXHEs

###

