[build]
command = "npm run build"
publish = "dist"

[dev]
publish = "src"

[[redirects]]
from = "/users/me"
to = "/"

[[redirects]]
from = "/movies/*"
to = "/"

[[redirects]]
from = "/genres/*"
to = "/"

[[redirects]]
from = "/directors/*"
to = "/"

[[redirects]]
from = "/login"
to = "/"